### ISSUE TITLE
Google Drive support further enhancements

### ISSUE THREAD

**Issue by maxhora** [iterative/dvc#2865]
This ticket is to keep track of required further improvements for Google Drive `remote` implementation after https://github.com/iterative/dvc/pull/2551 will be merged into `master`:

- [x] Processing of auth exceptions and printing more meaningful error message on failure. https://github.com/iterative/dvc/pull/2551#discussion_r348182771

- [x] Implement `gc` command support for `gdrive` ( `def remove(self, path_info)` overloading )

- [x] Validate resolved remote file object to have expected title ( `def resolve_remote_item_from_path(self, path_parts, create):`  )  

- [x] Simplify a few things using new and shiny `@wrap_prop` and `filter_errors` param of `@retry` from funcy 1.14 :) 

- [x] Make name -> id deterministic by choosing minimum id https://github.com/iterative/dvc/pull/2551#discussion_r350424816

- [x] Reimplement caching to have 2 entry points .path_info_to_ids() and .id_to_path_info(). The idea is to remove cache dictionaries completely, but it will require introduction of helper method which accepts parent_id, title and returns the actual id ( this method introduces 1 -> 1 relation between input and resulting remote id ). https://github.com/iterative/dvc/pull/2551#discussion_r350213128

- [x] Simplify `resolve_remote_item_from_path` https://github.com/iterative/dvc/pull/2551#discussion_r351940507

- [x] Protect `create_remote_dir` with lock. https://github.com/iterative/dvc/pull/2551#discussion_r350428630

- [x] Organize methods, params in ordered and unified way. https://github.com/iterative/dvc/pull/2551#discussion_r350152633

- [x] Enhance retrieving of HTTP error from GDrive API exceptions https://github.com/MaxRis/dvc/commit/783d8b610db9da2bdcee1817cd90366b435e81eb#r36184990

- [x] Create Iterative Google Drive account and Project to share client id and secret with final DVC users. Highest possible API usage limits quotas should be requested. Probably, it will be needed to have separate Google Project for CI. https://github.com/iterative/dvc/pull/2551#discussion_r351936393

- [x] Stop creating a path to the DVC remote root if it does not exist. Since Google Drive allows multiple folders with the same name (at least on in My Drive and one in Shared With Me) in case a path like `gdrive://root/storage` is used to access, collaborators see a `storage` empty folder after the first `dvc pull` attempt`. Instead we should just throw path does not exist.
- [x] Hide `/Users/ivan/Projects/test-gdrive/.env/lib/python3.7/site-packages/oauth2client/_helpers.py:255: UserWarning: Cannot access /Users/ivan/Projects/test-gdrive/.dvc/tmp/gdrive-user-credentials.json: No such file or directory
  warnings.warn(_MISSING_FILE_MESSAGE.format(filename))` on the first auth.

- [x] Reconsider `self.no_traverse = False`. Now even to pull a single file we run the full traversal. We can at least start listing only prefixes we need (e.g. `remote/0c/*` if we need to check if file `0c1234...ef` exists), we can use a parallel `exists` if we need to check less than 256 files, etc.
- [x] Put notes in docs that path like `gdrive://root` is not accessible by other people - that ID must be used to actually share data with other team members.
- [x] We should store one credentials file per remote
- [x] ~Do not allow empty root DVC remote path (except shared?). I think it can prevent a lot of strange issues. More on this here https://github.com/iterative/dvc/issues/3586~

- [x] Add `_download` progress https://github.com/iterative/dvc/issues/2865#issuecomment-560487931 -> #3722

- [x] Support file streaming in `dvc.api.open()` function (more details in #3408) and and update docs

- [ ] Add `import-url` support

- [ ] Check that `close()` is handles in the `dvc.api.open()` context manager.

- [ ] Support show URL in `dvc get` for Gdrive. We can generate a HTTPS link that can be used in a browser if user is authed. The same link as you would get if you download a file from UI.

- [ ] Fix credentials management for external repos (when we do `dvc get`, etc). We should have a way to cache them.

- [ ] Support external dependencies and outputs

- [ ] Check that `dvc get-url` functions properly. Need to come up with some credentials management.

- [ ] Review and add more tests if needed. Starting from API tests. 

- [ ] Add an explanation comment about how path vs ids work, all non 1-1 stuff. Someone running into GDrive for first time will appreciate https://github.com/iterative/dvc/pull/2551#pullrequestreview-311748384. Explain how we deal with it, how caching is involved too.

- [ ] Notify user on retries, keep the message on the screen if they are happening at a certain rate

- [ ] Consider raising an exception if there are multiple remote root directories with the same name

- [x] Move `_gdrive_*` helpers into a separate module `api` to simplify testing and reading the code

- [ ] When it's more or less stable make it trusted by default

- [ ] Check if there is a way to generate URLs for GDrive publicly available files to download them w/o auth. Examples: https://github.com/NVlabs/stylegan/blob/master/pretrained_example.py and https://github.com/NVlabs/stylegan/blob/master/dnnlib/util.py . `dvc get` ideally should work w/o asking to Auth for public objects.

- [ ] Improve performance, pass `fields`, consider using batch for exists call - https://developers.google.com/drive/api/v2/performance , see example here https://github.com/iterative/PyDrive2/issues/42

**Comment by shcheklein** [comment]
@MaxRis would be helpful if you include links to the discussions in the initial PR.

**Comment by MaxRis** [comment]
@shcheklein sure :+1:

**Comment by casperdcl** [comment]
also add _download progress (atm only uploads will provide progress)

**Comment by MaxRis** [comment]
@casperdcl thanks, have added this to the list

**Comment by MaxRis** [comment]
@efiop @Suor could you please review the order of priority for available things to be addressed in this ticket? Thanks!

**Comment by Suor** [comment]
@MaxRis maybe start from tests, then pick whatever you like.

**Comment by antonkulaga** [comment]
One more GDrive related issue that can be added to the list https://github.com/iterative/dvc/issues/3015

**Comment by tierney6** [comment]
Hi all, here is a screenshot of an issue I have with pushing to gdrive, and the subsequent creation of duplicate folders
![Screenshot from 2020-01-14 10-17-39](https://user-images.githubusercontent.com/52665405/72357158-80bd6680-36b8-11ea-8837-329569509194.png)

**Comment by efiop** [comment]
@tierney6 Thanks for reporting! @MaxRis is currently researching the issue. Stay tuned! 🙂

**Comment by jorgeorpinel** [comment]
(Added "Support file streaming in dvc.api.open() function (more details in #3408)" checkbox.)

**Comment by shcheklein** [comment]
@MaxRis @Suor do you remember what `Validate resolved remote file object to have expected title ( def resolve_remote_item_from_path(self, path_parts, create): )` was about?

**Comment by MaxRis** [comment]
@shcheklein just to put `assert` to check remote file has expected `title`. The idea was to add more validation of data received from GDrive API. For example, if we resolved file by `id`, it makes sense to validate the `title` with expected.

**Comment by shcheklein** [comment]
@MaxRis k, so meaning that we need to put an assert in the `_get_remote_item` ?

**Comment by MaxRis** [comment]
yes, exactly

**Comment by jorgeorpinel** [comment]
Woah this one is huge! Lots of things have been done too 🎉
Maybe move the remaining stuff into smaller issues and close this one? 🙂

**Comment by shcheklein** [comment]
@jorgeorpinel it's easier for me to manage it this way vs creating a long tail of small tickets. Let's keep it for now.

**Comment by jorgeorpinel** [comment]
>  Put notes in docs that path like gdrive://root is not accessible by other people - that ID must be used to actually share data with other team members.

I'm addressing this in https://github.com/iterative/dvc.org/pull/1096#pullrequestreview-386926510 👍 

Also, how about
- [ ] Add `dvc config gdrive.client_id` and `gdrive.client_secret` config options so you don't have to set it up per remote
?

**Comment by shcheklein** [comment]
> Also, how about

not sure about this, I don't see that much difference with other remotes and other params they have

**Comment by casperdcl** [comment]
Regarding adding `_download` progress, it's super hard because of the sheer stack of libraries and functions which were not designed for any form of iteration or callbacks in mind. There are a lot of places where it may look like progress could be added but really you'd only be monitoring a pipe after the file has been downloaded.

CC @shcheklein the stack:

- `dvc.remote.gdrive.GDriveRemote._gdrive_download_file()`
  - `gdrive_file.GetContentFile()`
  - `== pydrive2.files.GoogleDriveFile.GetContentFile()`
    - `FetchContent()`
      - `_DownloadFromUrl()`
        - `self.http.request()`
        - `== httplib2.Http.request()`
        - > The return value is [...] a string that contains the response entity body
          - `_request(self, conn : httplib2.HTTPSConnectionWithTimeout, ...)`
            - `_conn_request(self, conn, ...)`
              - `response.read()`
                - where `response == conn.getresponse()`
                - `== httplib2.HTTPSConnectionWithTimeout.getresponse()`
                - `== http.client.HTTPSConnection.getresponse()`
              - `http.client.HTTPResponse.read()`
                - `_readall_chunked()`
                  - can easily add progress here

Could monkey-patch doing:

```python
class Custom(http.client.HTTPResponse)
    def _readall_chunked(self):
        with Tqdm(...):
            ...

http.client.HTTPConnection.response_class = Custom
gdrive_file.GetContentFile()
http.client.HTTPConnection.response_class = http.client.HTTPResponse
```

but it's not pretty.

Opened upstream https://github.com/httplib2/httplib2/issues/165

**Comment by julsal** [comment]
Dear @shcheklein and @efiop, I'm starting working today on the "*add `import-url` support for GDrive*"

**Comment by plopd** [comment]
Dear @julsal, I am glad ur doing that. I am in need for that feature. I presume your current work is here: https://github.com/iterative/dvc/tree/gdrive-import

When do u expect to finish it?

**Comment by efiop** [comment]
@plopd We are migrating to fsspec right now https://github.com/iterative/PyDrive2/issues/113 and will ressurect `import-url` support for gdrive after that is sorted. ETA is August.

**Comment by plopd** [comment]
@efiop Great. Until then, I think we should remove the `gdrive` row, since really as of now, DVC is not supporting that protocol type. I got confused when I tried to use `import-url` for gdrive only finding out that it's not even available in the newest version.

**Comment by itcarroll** [comment]
With iterative/PyDrive2#113 closed, would it be possible to resume GDrive support for `import-url`?

**Comment by pmrowla** [comment]
cc: @efiop @isidentical

**Comment by pmrowla** [comment]
Closing this meta-ticket since it's very outdated. Separate issues for any missing features in the fssspec based gdrivefs should be opened as needed.
