### ISSUE TITLE
cleanups: todo after implementation of pipeline file

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#3693]
Tracking things to cleanup after #3676 is merged, in addition to suggestions in the PR:
- [x] Remove `tags` (will make life simpler) #3699
- [x] Split `Repo.collect()` for pipelines usage and stage gathering:
      Data related commands don't care about orderings of pipeline stages, whereas for pipelines,
      things are more complex than `collect()` can handle.
      This will also remove duplicated warnings currently on `reproduce`.
     **Workaround on #3699 for now**
- [ ] Why is there schema/serialization/deserialization in 3 places? Yeah, true.
- [ ] Parallel logics of loading/transforming/dumping of `Output`, `Dependency` and `Stages` for single stage and pipeline stages (Requires further investigation)
- [x] `StageLoader` is too dynamic.
- [x] Messed with `OutputDuplicationsError`: Make sure it's safe to remove current stage from error message.
- [x] (Feature Request) Some way to remove stage from both pipelines.lock and pipelines.yaml? (#3881)
- [x] Renaming utils/stage.py and functions inside it. (#3923)
- [x] Make `dump()` ordered (Only for Python==3.5).
- [x] `StageParams` and `OutputParams`

Of course, we need lots of tests and UI issues fixes, but this meta issue is only regarding code cleanups.

**Comment by jorgeorpinel** [comment]
I find the long name of options `--metrics` and `--plots` misleading, since they only accept one metrics/plot file. What about just `--metric` and `--plot`?

**Comment by efiop** [comment]
@jorgeorpinel Those are just consistent with the rest of the options: `--outs/--outs-no-cache/etc`. We might want to introduce an alias or support commas like we do in `--params`. But for now could leave as is.

**Comment by skshetry** [comment]
Most of the works is done. Next stage could be fixing the tests for the `repro`. (De)Serialization can be evaluated later, if we can do anything better. `StageParams` - the constants are something that we'll have to live with it.

Marking this as done for now.
