### ISSUE TITLE
repo: abstract erepo dvc/git handling into RepoTree

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#3811]
Issue for keeping track of what needs to be done for the tree abstraction

main tasks:

* [x] Support fetch/stream on `open()` (#3810)
* [x] Support saving from a tree directly to cache via `walk()`+`open()` (#3825)
* [x] Rework erepo to use new tree functionality (#3841)

other tasks:

* [x] `dvc list` should use `RepoTree` (#3841)

issues that should be fixed by this: #3611, #3087

**Comment by efiop** [comment]
Looks like we are done here. Feel free to reopen if i've missed anything.
