### ISSUE TITLE
snap: transition to v1

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#3872]
## Anyone arriving here getting this message:

![image](https://user-images.githubusercontent.com/10780059/85142798-c9b5b000-b240-11ea-9ad0-75e2310c7d56.png)

**Running:**

- `snap refresh --channel=latest/beta dvc` (to upgrade now), or
- `snap refresh --channel=v0/stable dvc` (to never upgrade)

**makes the message go away.**

Otherwise (*if you ignore the message*) you'll be upgraded from `v0` to `v1` **automatically** in a few days.

See https://dvc.org/blog/june-20-community-gems for some notes on upgrading to v1 (it's simple!)

----

## Maintainer notes:

Snap packages automatically update to the most recent version in a channel.

The default channel is **`--latest/stable`** (with the slash, yes; not my design choice) and normally we push tagged releases to it.

During breaking transitions (v0 to v1), though, we need a transition phase.

- [x] #3999 push the last `0.x` to a new `--v0/stable` channel
- [x] #3990 push the current `1.x` to `--v1/beta` and `--latest/beta`
- [x] push a new `0.x-final` to **`--latest/stable`**
  + [x] #3999 this issues a warning in the update available and error messages. This warning will state the 2 options for the user:
    * `snap refresh --channel=v0/stable` to stick to the old version
    * `snap refresh --channel=latest/beta` & use new API/syntax
    * `snap refresh --channel=v1/beta` & use new API/syntax. This would stop them getting warnings about `--v2` in future. Probably bizarre ("I wanna upgrade now but never again") and not worth mentioning this option.

After the transition period (say 30 days?) we go back to normalcy:

- [x] close the `--v1/beta` channel. Users on it will automatically get shifted to `--v1/stable`.
- [x] regularly push `1.x` updates to `--v1/stable` and **`--latest/stable`**

Some people will be be hit by errors at this stage, but ~~serves them right for ignoring the transition warning messages~~ we tried our best.

I'm not happy with the channel naming conventions either but such is life: https://snapcraft.io/docs/channels. In fact we have to manually request `--v0`, `--v1` etc.

- [x] ~~Please bump here~~done: https://forum.snapcraft.io/t/track-request-for-dvc/17735
- [x] #3999, #4038 sync `v1` and `v0` snap build improvements (e.g. #3990, #4037)
- related #3777
- realted https://github.com/iterative/dvc.org/issues/906

**Comment by casperdcl** [comment]
Got approval so could tick off a few items :confetti_ball:

```yaml
channels:
  latest/stable:    0.94.0               2020-05-23 (388) 104MB classic
  latest/candidate: ^
  latest/beta:      1.0.0a10             2020-06-08 (483) 107MB classic
  latest/edge:      1.0.0a10-5-g215ea494 2020-06-08 (487) 107MB classic
  v1/stable:        --
  v1/candidate:     --
  v1/beta:          1.0.0a10             2020-06-08 (483) 107MB classic
  v1/edge:          ^
  v0/stable:        0.94.0               2020-06-08 (388) 104MB classic
  v0/candidate:     ^
  v0/beta:          ^
  v0/edge:          ^
```

**Comment by casperdcl** [comment]
`v1/beta` closed now due to the official release of `dvc==1.0.0`. Currently:

```yaml
channels:
  latest/stable:    0.94.1            2020-06-25 (572) 101MB classic
  latest/candidate: ↑
  latest/beta:      1.0.2             2020-06-25 (569) 103MB classic
  latest/edge:      1.0.2-1-g64c1321c 2020-06-25 (570) 105MB classic
  v1/stable:        1.0.2             2020-06-25 (569) 103MB classic
  v1/candidate:     ↑
  v1/beta:          ↑
  v1/edge:          1.0.2-1-g64c1321c 2020-06-25 (570) 105MB classic
  v0/stable:        0.94.1            2020-06-25 (572) 101MB classic
  v0/candidate:     ↑
  v0/beta:          ↑
  v0/edge:          ↑
```

The only remaining item is - a few days from now - push `v1/stable` to `latest/stable`.

**Comment by casperdcl** [comment]
OK all done (the current master branch is also a release hence `edge` == `stable` at the moment):

```
channels:
  latest/stable:    1.1.7  2020-07-06 (608) 104MB classic
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      1.1.7  2020-07-05 (608) 104MB classic
  v1/stable:        1.1.7  2020-07-06 (608) 104MB classic
  v1/candidate:     ↑
  v1/beta:          ↑
  v1/edge:          1.1.7  2020-07-06 (608) 104MB classic
  v0/stable:        0.94.1 2020-06-25 (572) 101MB classic
  v0/candidate:     ↑
  v0/beta:          ↑
  v0/edge:          ↑
```
