### ISSUE TITLE
remote: separate remote/cache/tree into distinct concepts

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#3882]
Currently, `Remote` classes can contain methods that fall into three categories:
* remote operations - `upload`/`download`/etc
* cache operations - `save`/`checkout`/`link`/`move`/etc
* tree operations - `exists`/`isfile`/`isdir`/etc

Having all of these methods grouped into a single `Remote` class causes issues when we are dealing with paths that can come from different namespaces (trees). In particular, `LocalRemote` was originally written with the assumption that all paths for local remote or local cache operations are always filesystem paths, which is no longer the case given that we now need to support `GitTree` objects (via brancher and erepos).

Ex. `LocalRemote.exists(path)` is used in different places as a replacement for `os.path.exists()` to test if `path` exists in a local remote, if `path` exists in the local cache directory, and if `path` exists in a DVC repo, even though these are distinct operations.

Tasks:
* [x] separate remote/cache/tree methods
    * [x] tree methods -> `RemoteTree` (#3931, #3496)
    * [x] cache methods (#4019, #4041)
* [x] cache methods which take `path_info` parameters which can belong to a namespace other than `remote.tree` should take explicit `tree` parameters, so it is always clear what tree `path_info` applies to (#4019)
* [x] local cache should have its own tree instance that is separate from `repo.tree` (since local cache always operates on a filesystem working tree, but `repo.tree` does not) (#3991)
* [x] state should belong to local cache and not repo, and should only be used for working tree paths (#3991)

**Comment by efiop** [comment]
> remote operations - upload/download/etc

Maybe `upload/download` are actually related to the tree, but `push/pull/status` are definitely remote concepts that will use `upload/download` in respective trees.

**Comment by pmrowla** [comment]
Some minor cleanup left w/improving remote function naming, but after #4041 this refactor is pretty much done for now.

#4050 has been filed as a potential follow up issue.
