### ISSUE TITLE
completion: misc updates

### ISSUE THREAD

**Issue by casperdcl** [iterative/dvc#4070]
Follow-up to #3921 

- [x] update `shtab` dependency (`>=1.0.0`, or likely `>=1.1.0`) #4076
- [x] hide/skip certain subcommands (e.g. `daemon`) #4076
  + `shtab>=1.0.0` https://github.com/iterative/dvc/pull/3921#discussion_r442787136
- [x] hide/skip certain arguments & options #4076
  + `shtab>=1.0.0` <- https://github.com/iterative/shtab/issues/3
- [ ] introduce consistency calling DVC-files `targets`, other files `paths`, and directories `dirs`
- [ ] introduce consistency around leading vs trailing whitespace when linebreaking strings

**Comment by casperdcl** [comment]
based on the remaining checkboxes, this is no longer a `completion` issue (the completion issue is fixed). This is now a documentation issue - introducing naming consistency.

**Comment by efiop** [comment]
Let's close for now.
