### ISSUE TITLE
housekeeping tasks

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#4468]
Some of the things in addition to "[move to GHA](https://github.com/iterative/dvc/issues/4418)" and [changelog](https://github.com/iterative/dvc/issues/4023):
### CI
- [x] [Cache `pre-commit`'s caches on CI](https://pre-commit.com/#managing-ci-caches).
- [ ] [Run tests using lower bounds of requirements](https://github.com/PrefectHQ/prefect/blob/master/lower_bounds.py).
- [x] Stop building packages for PR.
- [ ] Check for [licensing issues](https://github.com/iterative/dvc/issues/1115) and [vulnerabilities for dependencies](https://github.com/iterative/dvc/issues/4153).

### Tests
- [ ] Look on how we can speedup tests. Maybe, we can remove a lot of redundant tests.
      Also, since these days we use `RepoTree` for external repo scenario, lots of tests involving `ls`/`update`/`import`/`get` could be reduced (which by the way are the slowest). At least mark them as `slow`.
- [x] Provide a way to selectively disable certain remotes when testing (or, make it optional by default, but run all on CI)?
      Something like `pytest --disable-hdfs`?
- [x] [Cover branches with `coverage`](https://coverage.readthedocs.io/en/coverage-5.2.1/branch.html#branch-coverage-measurement). #4760
- [x] Track failing/flakey tests, mark them as `flakey`.
- [ ] Why is docker running on unit tests? :smile_cat: 
- [ ] Configurable tests for remotes.
- [ ]  Consider using nox/tox for tests and pylint as these things are quite slow.
- [x] Add type hints (#4697).
- [x] Improve coverage to above 90% https://github.com/iterative/dvc/pull/4873

### Packaging
- [x] [Move to PEP 517/518](https://snarky.ca/what-the-heck-is-pyproject-toml/)? #6775 
- [x] Auto-update tests requirements. Either use dependabot or https://pyup.io.
- [x] [Auto-update pre-commit](https://github.com/iterative/dvc/issues/4404).
- [x] update restyler? How to keep that in-sync? Should we host our own docker images that are kept fresh?
- [x] Python 3.9 support "soon", actually we could start testing the support. Previous attempt: https://github.com/iterative/dvc/pull/3492
- [ ] Deploy on test.pypi.org

> These were the tasks I have been keeping tracks of on a separate list, thought I'd just dump. Not everything needs to fixed though. I could take them when I am free as well.

**Comment by efiop** [comment]
>  update restyler? How to keep that in-sync? Should we host our own docker images that are kept fresh?

Could consider disabling it. Seems like our linter job is doing the thing and we don't actually use restyler's PRs that often, as people tend to fix their patches when they see that linter complains.

**Comment by shcheklein** [comment]
Should we make some of them hacktoberfest tickets for the upcoming event?

**Comment by skshetry** [comment]
@shcheklein, sure, we can split this ticket.

**Comment by DiPaolo** [comment]
I've just spotted the missed year and copyright owner in LICENSE file:
https://github.com/iterative/dvc/blob/11382cc891c2c83e9f890d142adeeb22ce331243/LICENSE#L189

Should it be added as a housekeeping item as well?

**Comment by skshetry** [comment]
@DiPaolo, it is a boilerplate to copy in your _work_ (or, source files) that you want to specifically apply Apache License (and, replace that syntax with information).

Here's what [Apache License](http://www.apache.org/licenses/LICENSE-2.0#apply) says:
> To apply the Apache License to specific files in your work, attach the following boilerplate declaration, with the fields enclosed by brackets "[]" replaced with your own identifying information. (Don't include the brackets!)

Which is close to what's in the `LICENSE`:
https://github.com/iterative/dvc/blob/11382cc891c2c83e9f890d142adeeb22ce331243/LICENSE#L180-L184

To emphasize the last line:
> **The text should be enclosed in the appropriate comment syntax for the file format.**

**Comment by isidentical** [comment]
>  Cache pre-commit's caches on CI.

I guess we can simply use the official `pre-commit` action, `pre-commit/action`.

**Comment by skshetry** [comment]
Closing as stale.
