### ISSUE TITLE
checkpoints: minor table/UI issues

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#4709]
* [ ] checkpoints are not grouped properly during sorting (#4740)
* [ ] checkpoint branches are not sorted as expected by default - currently branches are returned alphabetically by branch name rather than by the most recent tip commit timestamp (#4740)
* [x] small floating point numbers are rounded to `0.0` instead of being displayed in scientific notation (#4730)
