### ISSUE TITLE
2.0 release checklist

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#4841]
2.0 will be a major release, which is a good chance to change some things we've been talking about in a potentially non-backward compatible way. Creating this ticket as a reminder for smaller things, as they might get forgotten while working on major planned stuff. Please feel free to add other points

* ~~rename .dvc/cache into .dvc/objects(or smth like that)~~ delayed for 3.0
* ~~get rid of CRLF conversion when computing md5~~ https://github.com/iterative/dvc/issues/4658 will be handled in 3.0 cache
* ~~either get rid of *.dvc files or at least fix the order of fields in it. E.g.~~ leaving for 3.0
```
- md5: 456789
  path: myfile
```
should really be
```
- path: myfile
  md5: 456789
```
so that we create less confusion when merging/deleting/--no-exec'ing.
- ~~change cache/remote format from:~~ https://github.com/iterative/dvc/issues/829
```
12/3456
98/7654
...
runs/
```
to
```
objects/  # for potential chunking https://github.com/iterative/dvc/issues/829
files/  # same as our current cache files, aka assembled objects
dirs/  # for .dir files, will help us quicker list .dir files in push/pull/status optimization (currently we just walk the whole remote looking for .dir files)
runs/
tmp/  # for .tmp files that we use for universal atomic upload/download (download .tmp + rename) ?
...
```
also worth making `files/` use `12/123456` format like git and our runs/ do instead of the current `12/3456`

- ~~Change .dir format~~ https://github.com/iterative/dvc/issues/829#issuecomment-711137723  https://github.com/iterative/dvc/issues/3791
- ~~Drop dvc run --single-stage https://github.com/iterative/dvc/issues/3936 ?~~ Not a blocker, could be removed later.
- ~~switch to sha256(512?) as a default algo and drop dosunix for md5~~ https://github.com/iterative/dvc/issues/829
- [x] <s>drop .dvc files for `dvc add/import` in favor of special fields in dvc.yaml </s> Decided to do that after 2.0. Clear that we will be moving this way so no reason to refactor old .dvc file schema.
- ~~revisit API exceptions~~ (ping @skshetry ) For 3.0
- ~~(optional) revisit config options for remotes, maybe get create an alias to later get rid of things like gdrive_*~~ a topic for discussion
- [x] adjust conda package to not install extras by default https://github.com/conda-forge/dvc-feedstock/issues/168
- [x] start [pushing](https://github.com/iterative/dvc/blob/363ad46326741a82279ddb23d5182d6c48225f15/.github/workflows/packages.yaml#L136) stable packages to v2 snap channel.
- [x] add docs for experiments, dvc.yaml 2.0 - besides technical docs, we'll need to revisit get started at the very least, tutorials
- [x] drop callbacks https://github.com/iterative/dvc/issues/1407
* ~~Consider forbidding backtracking output paths and maybe even wdir? Similar to `.gitignore`.~~ for 3.0
- [x] Check for 3.9 compatibility, including ~~`dulwich`~~/~~`pyarrow`~~/`ruamel-yaml` and maybe others  (ping @skshetry)
- [x] Make dvc config/remote load all configs by default and introduce `--repo` for the current behavior.
* ~~Remove schema validation during run-cache dump?~~
- [x] ~~Drop pyinstaller? (check analytics to see % for binary packages) https://github.com/iterative/dvc/issues/936~~ having a standalone package is still needed for some scenarios
- [x] get rid of can_be_skipped https://github.com/iterative/dvc/issues/5368
- [x] straight to remote/cache https://github.com/iterative/dvc/issues/4520
- [x] reconsider `dvc add` behavior https://github.com/iterative/dvc/pull/5412#discussion_r570385996 @efiop (might require `dvc add` doc change)

**Comment by pared** [comment]
Should we consider including checksum type into `files` (eg current `cache` -> `files/md5`)? We don't have to support new checksums right away, but that would give us opportunity to make checksum "pluggable".

**Comment by skshetry** [comment]
Can we start showing colourful messages?

**Comment by jcpsantiago** [comment]
> Can we start displaying colourful messages?

Yes please! I had to code it myself :p
<img width="618" alt="Screenshot 2020-11-12 at 12 23 46" src="https://user-images.githubusercontent.com/789796/100235135-4d7c7280-2f2c-11eb-86c4-7ba9a7d4501b.png">

**Comment by skshetry** [comment]
> > Can we start displaying colourful messages?
> 
> Yes please! I had to code it myself :p
> <img alt="Screenshot 2020-11-12 at 12 23 46" width="618" src="https://user-images.githubusercontent.com/789796/100235135-4d7c7280-2f2c-11eb-86c4-7ba9a7d4501b.png">

That's looks really good. Would you mind sharing what you are using?

**Comment by jcpsantiago** [comment]
The “header” is at the top of all my scripts: left (yellow) is the name of the stage (hard coded for now, because I can’t get it from DVC into the script) and the left is the current model, passed to the script as a parameter using the amazing upcoming `foreach` (https://github.com/iterative/dvc/pull/4734)

The rest are log messages which also make use of the current model coming from `foreach`.

I’m using R and the `cli` and `crayon` packages to do this, but the same could be done easily to the DVC code to “announce” each stage.

**Comment by efiop** [comment]
@skshetry I guess there is no reason to do it before 2.0 release, as it is not really breaking backward compatibility or anything like that. The other checkboxes are often such that we actually need to break stuff :slightly_frowning_face:
