### ISSUE TITLE
experiments: checkpoints cleanup/research issues

### ISSUE THREAD

**Issue by pmrowla** [iterative/dvc#5247]
* [x] Investigate whether we can have finer control over `rich` table column collapse behavior - `--no-pager` with wide tables results in several empty columns that make output unreadable (#5381)
* [x] Preserve metrics/params column order (related to #5009)
* [x] Add short option for `dvc exp show --all-commits` (#5361)
* [x] `dvc repro` should just fail on `checkpoint = true` stages instead of issuing warning and handling as a persist out (#5258)
* [x] ~~`exp res` should be possible after `run --no-exec --checkpoints ...`~~
* [x] Unify `run/resume`, for checkpoints re-introduce `reset` (#5351)
* [x] Investigate duplicate commit issue from #5311
