### ISSUE TITLE
2.0 meta release plan

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#5367]
High-level ticket for tracking to the DVC 2.0 release. Add/edit/remove issues as needed and prioritize which are critical for 2.0.

- [ ] Parametrization (@skshetry):
  - [x] #5312 
- [ ] Experiments (@pmrowla):
  - [ ] Checkpoints:
    - [x] #5247 
    - [x] #5404
  - [ ] Run
    - [x] #5472  
  - [ ] Show:
    - [x] #5311
    - [x] #5381  
    - [ ] #5451 
    - [X] #5516
  - [ ] Apply
  - [ ] GC
  - [ ] Sharing
- [ ] Stage add (@skshetry):
  - [x] #5342
- [ ]  To-cache/to-remote (@isidentical):
  - [x] #4520 
- [ ] Lower-level issues (@efiop I added anything I thought might be needed here, I can delete whatever isn't needed):
  - [ ] #4841
  - [x] #5255?
  - [ ] #5256?
  - [x] #5302?
  - [ ] #5356?
- [ ] Docs (@jorgeorpinel):
  - [ ] https://github.com/iterative/dvc.org/issues/2026
  - [ ] https://github.com/iterative/dvc.org/labels/2.0%20release
  - [ ] https://github.com/iterative/dvc.org/issues/2228
- [ ] Dvclive

**Comment by skshetry** [comment]
@dberenbaum, high level issue for parametrization is https://github.com/iterative/dvc/issues/3633 which is closed. There's a QA ticket in https://github.com/iterative/dvc/issues/5312 though.
