### ISSUE TITLE
executor: setup and configure executors

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#6263]
Meta-issue. Please link related tickets back to this one.

### User story

I want to spin up an executor and tear it down.

### Requirements

* Define Terraform resources in DVC config files
* Create, update, and destroy resources from within DVC

### Tasks
Config-only commands:

* [x] `dvc machine add` (#6462)
* [x] `dvc machine remove` (#6462)
* [x] `dvc machine list` - (#6480)
* [x] `dvc machine modify` - (#6480)

Terraform wrapper commands
* [x] `dvc machine create` (#6462)
* [x] `dvc machine destroy` (#6462)
* [x] `dvc machine rename` (#6481)
* [x] `dvc machine status` - (#6482)
* [x]  `dvc machine ssh` - (#6483)

**Comment by dberenbaum** [comment]
Terraform resources should be configurable in `.dvc/config` files - including support for system, user, etc. configuration.

**Comment by casperdcl** [comment]
related: https://github.com/iterative/terraform-provider-iterative/issues/164#issuecomment-901084421

**Comment by dberenbaum** [comment]
I'm a little concerned that we are using up the namespaces for `machine`, especially `list` and `status`. We will need some command that outputs table-like info about each machine (similar to `docker ps`): what machines have been created, how long have they been running, are they idle or running an experiment, etc. Where will that go?

**Comment by pmrowla** [comment]
I think anything that is aware of whether or not some instance is running experiments or not would go under `dvc exp`. `machine list/status` are more like `docker machine ls`, which just tells you about machines that have been created and/or booted (and the separation between `list` and `status` is that `list` shows .dvc/config entries, and `status` shows terraform status). `machine` is currently not aware of anything that is actually running on the instance itself.

`docker ps` displays the state of deployed docker containers that are running on some machine (that may or may not have been created with `docker machine`). This is more like the actual "executor" concept in DVC (i.e. keeping track of running/deployed experiments, which is separate from terraform/machine instance status). It seems like we will eventually just want a separate `machine ps` or `exp ps` command that would be the equivalent to `docker ps` and shows the state of running experiments - including whether or not a potential executor is idle.

**Comment by pmrowla** [comment]
I guess it's possible that we may end up not needing `machine status` (in favor of the `ps` command), but IMO there is a distinct difference between "knowing the IP and boot state of a terraform instance" vs "whether or not DVC experiment related processes are idle on some named 'DVC executor' instance" (and I think having 2 separate commands here makes sense)

We could also potentially merge `list` and `status` into a single (DVC config) `machine list/ls` where we would have some CLI output that lists the .dvc/config entries for machines and then nests the terraform boot/IP/etc status information underneath each DVC-config entry

But this all seems like UI decisions that can be made further down the line once we actually have the underlying functionality working

**Comment by karajan1001** [comment]
`docker` has `docker images` to list images and `docker ps` to list containers. Here `machine status` only exists when `machine` was created. So more close to the container than the images?

**Comment by dberenbaum** [comment]
Good points. Let's set aside "are they idle or running an experiment" and assume that goes under `dvc exp`. 

> But this all seems like UI decisions that can be made further down the line once we actually have the underlying functionality working

I agree we don't want to spend a lot of time going back and forth on the UI or worry about future needs, but unless we have a separate story to come back and revisit the UI for each of these commands, I think we need to try to follow our UI guidelines in these PRs as best we can. For example, I think we need to address https://github.com/iterative/dvc/pull/6602#issuecomment-920174006 to consider #6480 done.

**Comment by dberenbaum** [comment]
From https://github.com/iterative/dvc/pull/6649#issuecomment-931843157:

> @dberenbaum Regarding the terraform CLI output, we originally decided to leave it enabled by default (and not suppress it) since there is no other way for us to reflect status while terraform ... commands are running (and we expect them to be slow).
>
> Since we can't hook into the terraform process itself to setup any kind of status callbacks, the only other option on the DVC UI side would be to just display something like a spinner (we can't provide any progressbar-like estimate of when the terraform command will complete).

`dvc machine add` is the most complex and likely longest-running command, and the progress it reports is at most (depending on whether the resource already exists):

```
iterative_machine.myaws: Destroying... [id=iterative-2i07hddg43zyp]
iterative_machine.myaws: Destruction complete after 1s
iterative_machine.myaws: Creating...
iterative_machine.myaws: Still creating... [10s elapsed]
iterative_machine.myaws: Creation complete after 18s [id=iterative-27smam0qwszht]
```

It seems like the only info users gain is whether the machine is being destroyed (which should be short) or created. Not sure if there's any way to collect that info. 

I don't think any other machine commands are likely to have more than one step, which makes the terraform output useless as a progress tracker for them (or whether they are likely to need progress tracking).

The raw terraform output might be useful for debugging, but I'm not so sure it's always needed.

**Comment by pared** [comment]
When talking about executor, have we been considering a use case where only particular stage gets executed on executor?

context:
https://discord.com/channels/485586884165107732/485596304961962003/908007017241788497

**Comment by dberenbaum** [comment]
> When talking about executor, have we been considering a use case where only particular stage gets executed on executor?

It's not in the plans right now, but it's been discussed. Doing it once should be easy by specifying a single stage to run as a remote experiment. Having `dvc.yaml` specify the permanent machine to use for each stage is more complex but should be doable.
