### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#7093]
```[tasklist]
## Data Management
- [ ] https://github.com/iterative/dvc/issues/4658
- [x] #9531 (@efiop)
- [x] Rename `dvc add --jobs` to `--remote-jobs` (frequently gets confused with core.checksum_jobs)
- [ ] https://github.com/iterative/dvc/pull/9591
```

```[tasklist]
## Experiments and Pipelines
- [ ] #9221
- [x] add `dvc stage add --run`
- [x] [Remove Stage-level vars](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#:~:text=Stage%2Dspecific%20values%20are%20also%20supported) (@skshetry)
- [ ] ~`dvc exp push` changes? (see https://iterativeai.slack.com/archives/C01116VLT7D/p1686570450222809?thread_ts=1686321601.633079&cid=C01116VLT7D)~ decided not to make breaking changes now; will revisit dropping `--rev HEAD`
```

```[tasklist]
## Deprecations
- [x] https://github.com/iterative/dvc/discussions/5940. (@skshetry )
- [x] Remove [~`exp gc`~](https://github.com/iterative/dvc/issues/7991), [~`exp init`~](https://github.com/iterative/dvc/issues/9267), [~`exp show --html`~](https://github.com/iterative/dvc/issues/9268), ~`exp show --pcp`~.
- [x] Deprecate `dvc add --recursive` flag.
- [x] Remove `dvc run`.
- [x] Remove `--show-json`/`--show-csv`/`--show-md` in favor of existing `--json`/`--csv`/`--md` flags.
- [x] ‍‍‍‍‍[Drop top-level plots definition as a dictionary, can be defined as a list instead](https://github.com/iterative/dvc/pull/8412).
- [x] Drop 1.0 `dvc.lock` format support.
- [x] Soft deprecate `desc`/`type`/`labels`/`meta` in `dvc.yaml` and `.dvc` files, now that we have artifacts (drop CLI flags, `dvc data ls`, and drop them from docs).
- [x] https://github.com/iterative/dvc/issues/9457 (and replace with `--message` short flag)
- [x] Deprecate dvc add --file (obscure and more likely to confuse than help)
```

## Other [release blockers](https://github.com/iterative/dvc/issues?q=is%3Aopen+is%3Aissue+label%3Arelease-blocker)

- [x] https://github.com/iterative/dvc/issues/9530
- [x] https://github.com/iterative/dvc/issues/9541
- [x] https://github.com/iterative/dvc/issues/9584

### Studio Readiness for 3.0 release
- [ ] https://github.com/iterative/studio/issues/5944

**Comment by dmpetrov** [comment]
That's a great summary of the coming changes. I'd appreciate it if some of the items could be clarified.

> * [ ]  introduce `data`(name is subject to change) section in dvc.yaml for data (also need to look into imports)

Should we introduce similar for `metrics`, `plots`?

> * default hash change.

It would be helpful if you could clarify this.

> * [ ]  deprecate `--show-*` flags
> * [ ]  remove `--show-vega` flag

Where does this requirement come from? How users will generate png files from our templates in CI/CD?

**Comment by efiop** [comment]
> Should we introduce similar for metrics, plots?

Sure, seems like plots will be the first. Just trying to mark this new approach with introducing separate sections.

> It would be helpful if you could clarify this.

CC @pared

**Comment by pared** [comment]
> deprecate --show-* flags

I guess this is about migrating `--show-json` and friends to `--json` and similar, just to make it shorter.

>  remove --show-vega flag

We recently introduced '--json' [for plots](https://github.com/iterative/dvc/pull/7074). It's not official yet, but since we support images, we will need to do it sooner or later (officially) in automation scenarios too. In that case `--show-vega` does not make sense, because its limited to only one plots type. Results obtained by `--show-vega` can be achieved by specifying singular target for `--json` so there is not too much argument for keeping it.

**Comment by dberenbaum** [comment]
@pared I thought `--json` was a hidden option for VS Code?

For the vega example in https://cml.dev/doc/cml-with-dvc using vl2png, how can this be handled with `--json`?

**Comment by pared** [comment]
> @pared I thought --json was a hidden option for VS Code?

Well, it seems to me that we will have to start supporting it. It kind of does not make sense from user perspective, to support vega as json and not do the same for images - our current problems "where to store the results" should probably not affect the enduser.

> For the vega example in https://cml.dev/doc/cml-with-dvc using vl2png, how can this be handled with --json?

Some json manipulation is needed for that. In this particular example:
```
dvc plots diff \
            --target classes.csv \
            --template confusion \
            -x actual \
            -y predicted \
            --json master | jq '."classes.csv" | .[0]' >> vega.json
```

**Comment by daavoo** [comment]
> > For the vega example in https://cml.dev/doc/cml-with-dvc using vl2png, how can this be handled with --json?
> 
> Some json manipulation is needed for that. In this particular example:
> 
> ```
> dvc plots diff \
>             --target classes.csv \
>             --template confusion \
>             -x actual \
>             -y predicted \
>             --json master | jq '."classes.csv" | .[0]' >> vega.json
> ```

Ping @iterative/cml . I think `send-comment` with vega plot is a widely used exampled

**Comment by pared** [comment]
> I think send-comment with vega plot is a widely used example. Opened issue

Good idea though let's not solve it until we agree on whether `--json` is what we want and that we remove `--show-vega`.

**Comment by karajan1001** [comment]
One question here, because there might be some `subrepo`s deep inside directories. Even if we had deprecated `.dvc` files. We might still need to walk through the whole structure to find out all of the stages in `subrepo`s. Or We will need to make a clear and better way to handle `subrepo`s.

**Comment by skshetry** [comment]
@karajan1001, we do not traverse into subrepos except for `dvc list`. `dvc.api`/`dvc get`/`dvc import` uses particular logic to find subrepos, but does not require it as we avoid getting files from subrepos. There have been discussions on getting rid of the "subrepos traversal" completely as it's not worth it with the complexity it introduces.

**Comment by dberenbaum** [comment]
Additional items:

- [ ] Remove all "new in 2.0" and "experimental" flags from docs
- [ ] Deprecate `exp gc` (see #7991)
- [ ] Deprecate `dvc exp run --run-all/-j` flags and consider how to replace with top-level exp commands to start the queue (see https://github.com/iterative/dvc/discussions/8123)
- [ ] Consider deprecating `run` and replacing with `dvc stage add --run` (see https://github.com/iterative/dvc/issues/5846)
- [ ] Plots: consider dropping `.dvc/plots` as default location (no longer needed) (cc @pared)
- [ ] Plots: consider dropping `rev` field in Vega templates and rely on `dvc_data_version_info` (cc @pared)
- [ ] Plots: CLI support for top-level plots (see https://github.com/iterative/dvc/issues/7753)

**Comment by dtrifiro** [comment]
Additional items:

- [ ] Plots: drop support for plots top-level definition as mapping (see https://github.com/iterative/dvc/pull/8412)

**Comment by dberenbaum** [comment]
- [ ] Config: set core.autostage true by default?

**Comment by skshetry** [comment]
@dberenbaum, can you please push these items/tasklist to the top comment? The item does not have to be a sure thing to be on top.

**Comment by skshetry** [comment]
> remove read-only support for dvc-1.0 lockfile and 1.0-lockfile-to-2.0 migrator. 1.0 lockfile was not versioned, 2.0 got schema keyword for version info. ([Implementation](https://github.com/skshetry/dvc/blob/e9244924d728bf9ca4ac7ea00b8e4b8a468ead53/dvc/dvcfile.py#L373-L377), introduced in https://github.com/iterative/dvc/pull/5128)

Hopefully, we can remove this in 3.0.

**Comment by skshetry** [comment]
If there’s no strong opinion, I’d like to deprecate `—show-*` flags soon (let’s say in 2.35 for example). With deprecate, I mean that they will be hidden from CLI help. We don’t document them in docs for a long time now. We can remove them in 3.0.

**Comment by jorgeorpinel** [comment]
>  start obsoleting data .dvc files

May I ask what this looks like? Meaning what replaces them; I remember discussing a new top-level `data` section in dvc.yaml (can't find the issue now), is that still being considered?

In general though, I'm not sure I'm seeing huge changes that warrant a major semver update. IMO going to 3.0 is an opportunity for hyping and devrel activities (think Python 2 vs 3, how much anticipation there was, etc.) so it should be tied with something really big. I feel we're definitely in 2.0 ever since dvc.yaml was introduced, and maybe we could've gone 3.0 during the DVC Experiments release(s), but since we didn't, should we wait for something of that scale?

**Comment by skshetry** [comment]
> since we didn't, should we wait for something on that scale?

These days, I believe DVC should be on calver. With that, we'll have a yearly cadence on release and we can hype things up. We can break compatibility on `year++` release if we like.

**Comment by daavoo** [comment]
> These days, I believe DVC should be on calver. With that, we'll have a yearly cadence on release and we can hype things up. We can break compatibility on year++ release if we like.

+1 for calver

**Comment by dberenbaum** [comment]
> These days, I believe DVC should be on calver. With that, we'll have a yearly cadence on release and we can hype things up. We can break compatibility on year++ release if we like.

If we use calver and we want to make a breaking change before the next year, what do we do?

**Comment by skshetry** [comment]
> If we use calver and we want to make a breaking change before the next year, what do we do?

Yeah, it is a bit limiting in that way. In practice, I don't think we'll break it that often.

Also, that's only applicable when we want to mix semver with calver. If we don't want to, any new version can be a breaking change (and that's left up to the user to determine).

**Comment by skshetry** [comment]
We also haven't dropped .dvc file support for the pipeline stages, and we have kept feature parity between dvc.yaml and .dvc files.
They support params, metrics, plots (to some extent), all recent annotations features, desc, etc. It would be nice to remove support for them even if we keep `.dvc` files for data management.

**Comment by shcheklein** [comment]
> Plots: consider dropping rev field in Vega templates and rely on `dvc_data_version_info` (cc @pared)

@dberenbaum @daavoo @mattseddon do you have any insights on this? We use `rev`, `filename`, etc in group by and other parts of the Vega templates. If we nest them into `dvc_data_version_info` we might need to then apply `flatten` transformation in Vega templates to deal with values + quite a lot of changes to Studio, VS Code, etc. I wonder what was wrong with including `filename`, `rev`, `field` as regular fields into datapoints?

**Comment by daavoo** [comment]
> @dberenbaum @daavoo @mattseddon do you have any insights on this? 

We could take a step back and meet to define what format would be better for VSCode given today's features and needs. 
The `--json` flag is hidden, not documented, and most likely used only by VSCode. I don't think we need to wait for `3.0` to change the schema, we have already changed it in `2.X` releases.

**Comment by dberenbaum** [comment]
@daavoo I think it was not about `--json` but about getting rid of `rev` field everywhere in favor of `dvc_data_version_info`. We may have to dig through the discussions and PRs to determine why it was done this way unless @mattseddon remembers.

**Comment by dberenbaum** [comment]
> We use `rev`, `filename`, etc in group by and other parts of the Vega templates. If we nest them into `dvc_data_version_info` we might need to then apply `flatten` transformation in Vega templates to deal with values + quite a lot of changes to Studio, VS Code, etc. I wonder what was wrong with including `filename`, `rev`, `field` as regular fields into datapoints?

@shcheklein Coming back to your question here, I think it was because we needed the existing `rev` to be the concatenated value of everything to make it work with old plots templates that don't know about `filename` or `field`. Therefore, we couldn't use `rev` for solely the revision info.

**Comment by shcheklein** [comment]
@dberenbaum yep, I see that we need more info. What I'm trying to understand is the difference in two approaches:

1. Introduce this nested `dvc_data_version_info` structure and keep expanding it (with `filename`, `rev`, etc, etc)
2. Keep these all fields on the data point level.

With both approaches I believe we can achieve the same result, unless I missing something (?). But in case of introducing the additional layer of nesting that would complicate all the templates potentially (e.g. we would need to use `transofrm` for flatten the fields to be able to group by, etc).

Downside of the second option - names collision - we are effectively making `rev`, `field`, `filename`, etc reserved names. This still can and should be mitigated by prefixing them with something (`__rev` or `__dvc_rev`).

Does it make sense or maybe I'm missing some context from your question ...

**Comment by skshetry** [comment]
A breaking change related to the packaging that I want to do is move `dvc.utils.pkg` to just `dvc.pkg` or `dvc.build`. That prevents us from importing `dvc.utils` when we want to read just `pkg`. Although this does not require 3.0.

(Side note: It'd be nice to figure out a way to set `pkg` type without changing source code, as it does not make the build reproducible, i.e what I create locally is not going to be the same as what we upload for the same commit.)

**Comment by dberenbaum** [comment]
Added an item to push/pull run-cache by default (don't see why we wouldn't do this).

**Comment by dberenbaum** [comment]
Added two more items that might require some discussion:

- [ ] Deprecate or change `dvc exp init` (it's outdated relative to the current recommended way to onboard to experiments)
- [ ] Deprecate `dvc exp show --html` (we should probably do this outside of the CLI if we want a parallel coordinates plot)

**Comment by dberenbaum** [comment]
> * Drop External outputs

I think this needs a discussion like #9221 for what should replace it. I still see it being used frequently. For example, https://discord.com/channels/485586884165107732/1089975153854779412 and https://discord.com/channels/485586884165107732/1089910570888724520.

**Comment by dberenbaum** [comment]
Added my thoughts on priorities in the checklist:

* p1: blocker for 3.0
* p2: nice to have if we have time
* p3: not in 3.0 plans

**Comment by skshetry** [comment]
I took the liberty of cleaning up the checklist with tasks that we agree on. Other undecided tasks are still there on a collapsed section. If anyone feels like they should be part of 3.0, feel free to move them up.

**Comment by dberenbaum** [comment]
Thanks @skshetry! I dropped items from TBD that seemed like we would obviously not get to, and then I moved a few down to TBD:

* dos2unix - unclear to me if this is still something we plan to prioritize (@pmrowla @efiop)
* #9272 - unclear to me if we still want to do this (@daavoo)
* Replace dvc.main.main() with dvc.cli.main - unclear what is the level of effort and why we want it (@skshetry)

Please give your feedback on those **and the other items in the TBD list** so we can either prioritize them or drop them. Thanks!

**Comment by skshetry** [comment]
It’s literally deleting just this file. 

https://github.com/iterative/dvc/blob/37858be02fdef056801d917aa167ea300a3afa67/dvc/main.py#L1-L2

It’s already an alias to dvc.cli.main, and we are not using it internally. In the past, we have suggested to use main() as an API. It doesn’t strictly require 3.0, but I didn’t want to break.

**Comment by pmrowla** [comment]
I would prefer to drop the dos2unix behavior now

**Comment by dberenbaum** [comment]
@pmrowla Moved it up.

**Comment by daavoo** [comment]
> https://github.com/iterative/dvc/issues/9272 - unclear to me if we still want to do this (@daavoo)

I think we should drop it in favor of proper built-in support for markdown output (https://github.com/iterative/dvc-render/issues/123)

**Comment by dberenbaum** [comment]
@dmpetrov @shcheklein If you have any inputs on what should/shouldn't be included (for example, dropping checkpoints), please share.

**Comment by skshetry** [comment]
@omesser, it'd be better to move the Studio issues to its own repository, since they are private and unrelated to dvc's release.

**Comment by omesser** [comment]
@skshetry they are already on studio, just referenced here to keep track. 
Those issues are in fact related to the dvc 3.0 release on the product side (3.0 release is more hollostic to the ecosystem and not just a github release on this repo. We will use this opportunity to create some PR material).
I can create a placeholder umbrella issue there and dereference those, no objection, but all it will achieve is hide the issue titles from open source users reading this issue :man_shrugging: no problem, I will do that if you think it will be cleaner for this public facing issue. 
In any case the release material and messaging will refer to the larger DVC ecosystem's new capabilities including Studio features

**Comment by skshetry** [comment]
The issue is more about changes that's going to happen for 3.0, let's keep it at that. The Studio issues are follow-ups, similar to many other issues that have to happen around or after 3.0 release like docs, release announcement, etc.

**Comment by skshetry** [comment]
Working on 1.0 lock format deprecation.

**Comment by omesser** [comment]
> The Studio issues are follow-ups, similar to many other issues that have to happen around or after 3.0 release like docs, release announcement, etc.

No they are part of the 3.0 public release (product release, not technical github release for the DVC repo).
We can track them both and not have separate dvc-pre-requisite-release-checklist and dvc-product-release-checklist 🤔

**Comment by dberenbaum** [comment]
Some possible ideas to add looking through `dvc add` options:

* Deprecate `dvc add --file` (obscure and more likely to confuse than help)
* Rename `dvc add --jobs` (frequently gets confused with `core.checksum_jobs`)

**Comment by skshetry** [comment]
Two more proposals from my side:

- [ ] [Remove Stage-level vars](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#:~:text=Stage%2Dspecific%20values%20are%20also%20supported). I haven't seen this being used and makes implementation complex.
- [ ] Make `dvc exp push` work by default, or remove the need for explicit `remote` argument.
      (If we make `dvc exp push` work by default, what should it push?)

**Comment by dberenbaum** [comment]
>     * [Remove Stage-level vars](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#:~:text=Stage%2Dspecific%20values%20are%20also%20supported). I haven't seen this being used and makes implementation complex.

😅 https://discord.com/channels/485586884165107732/1111557378735865856/1111636564183883876

It's not clear to me whether the stage-level vars are needed there. @skshetry Maybe you have an idea for how else to handle that use case?

>     * Make `dvc exp push` work by default, or remove the need for explicit `remote` argument.
>       (If we make `dvc exp push` work by default, what should it push?)

I've come around to not minding the explicit `remote` requirement since it has occasionally saved me from accidentally pushing to `origin` when it was an upstream remote (like when I clone a demo project but don't want to mess with the studio demo). Especially now that we have VS Code to make pushing easier, I don't mind keeping the CLI explicit.

**Comment by dberenbaum** [comment]
When dropping external outputs, can we continue to support `--outs-no-cache` with external paths, and can we allow them without the `--external` flag (which we can drop)?

**Comment by dberenbaum** [comment]
> > ```
> > * [Remove Stage-level vars](https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#:~:text=Stage%2Dspecific%20values%20are%20also%20supported). I haven't seen this being used and makes implementation complex.
> > ```
> 
> 
> 😅 https://discord.com/channels/485586884165107732/1111557378735865856/1111636564183883876
> 
> It's not clear to me whether the stage-level vars are needed there. @skshetry Maybe you have an idea for how else to handle that use case?

@skshetry It turns out they aren't needed in that case, so I'm on board to drop them.

**Comment by aschuh-hf** [comment]
Hi, I posted this [question regarding external outputs on Discord](https://discord.com/channels/485586884165107732/485596304961962003/1111663148777340989) and am moving the discussion here as suggested.

I currently moved a larger scale data analysis from our local server to run in AWS using a Ray Cluster (https://www.ray.io/). The different steps are implemented as individual Ray jobs which are compiled into a reproducible pipeline with DVC using a `dvc.yaml`. Because the execution of jobs / stages is in AWS, and because the size of the data is too large to store locally, the inputs and outputs of each stage are external AWS S3 URIs. As part of this I run into one or the other issue (stage output always "not in cache" even right after `dvc commit -f` was run; error to run stage the first time because S3 URI prefix does not exist) indicating some bug in DVC in regards to external outputs (still need to file GitHub issues for these).

However, looking at this roadmap for the next major release version 3.0, I can see that there is a To-Do item that reads "drop external outputs". So my more immediately pressing questions are:
- Will AWS S3 URIs for stage inputs and outputs no longer be supported from DVC version 3.0 onwards?
- What is the recommendation for being able to run large reproducible data processing in the cloud (AWS)? All stage outputs should only live in AWS S3. Stage scripts stream the data directly from/to this remote storage.

An example `dvc.yaml` would look something like:
```
vars:
- s3_uri_prefix: s3://bucket/prefix
stages:
  stage_1:
    cmd: ray job submit --working-dir . -- python stage_1.py --output ${s3_uri_prefix}/stage_1
    deps:
    - stage_1.py
    outs:
    - ${s3_prefix}/stage_1:
        push: false
  stage_2:
    cmd: ray job submit --working-dir . -- python stage_2.py --input ${s3_uri_prefix}/stage_1 --output ${s3_uri_prefix}/stage_2
    deps:
    - stage_2.py
    - ${s3_uri_prefix}/stage_1
    outs:
    - ${s3_uri_prefix}/stage_2:
        push: false
```

I'd appreciate any pointers as to how DVC would still fit into the picture here.

**Comment by dberenbaum** [comment]
@aschuh-hf I'm personally torn on this decision, but ultimately (as you mentioned) there are a lot of bugs and problems with the way we handle external outputs today. The goal is not to give up on the use case you mention above (it's more important than ever), but to build a better solution for ti.

Besides staying on DVC 2.x for now, you should be able to continue working with pipelines streaming data to/from s3 if you set `cache: false`. Given that your data is large, do you mostly use dvc to manage your pipeline, or do you use the cache and checkout older versions of your data?

To cache your s3 pipeline outputs, I hope we can use [cloud versioning](https://github.com/iterative/dvc/issues/8411) to help address this, so please also comment there with your thoughts. This could mean that DVC no longer has to do slow operations like caching an extra copy of your data, so I hope it will end up improving the workflow in the end.

**Comment by aschuh-hf** [comment]
Thanks, @dberenbaum, for adding some more motivation for potentially deprecating it.

As a matter of fact, my current use case was for a data preprocessing and model evaluation pipeline. I am indeed mostly using the `dvc.yaml` in this context as a means to document the commands I run alongside the source code used to make it easier to reproduce the same results another time or re-running the same steps with different inputs. I don't for this purpose care too much about the caching of past results apart from the current run, and if I were to revert back to an earlier version I would be OK with spending the compute again to reproduce the outputs. Cloud versioning seems would fit also well in, though we haven't enabled this for the S3 bucket we are using for such experimental runs at the moment.

I can also confirm that the time spent on caching and re-computing hashes is quite a bottleneck given how slow it is for thousands of S3 objects. Given the use of a Ray cluster, the time waiting for DVC perform these operations is far greater than the actual execution of the individual stage commands.

It would mostly be sufficient for my use case here if `outs` and `deps` would merely define the dependency graph.

It would, however, also be useful if stages would still only re-run if the inputs, parameters, or command of a stage changed. If that can be done via version information provided by cloud versioning backends, that sounds good.

**Comment by efiop** [comment]
One last thing we forgot to include is to stop validating cache on every minor operation. This is a leftover from the past where symlink/hardlink were default and you ran a greater risk to corrupt your cache. These days we default to reflink/copy, so there is no reason really to validate cache on every operation like `checkout`. We should instead only validate cache where we really need to (before push?) and just introduce `dvc cache check` (or something like that) for manual validation.

**Comment by dberenbaum** [comment]
> In practical terms, I don't think we document that certain operations check cache, so we are not really tied to 3.0 release and can just stop doing it whenever.

Why don't we create a separate issue for it then and just make it high priority so we get to it soon?

**Comment by skshetry** [comment]
Stage-level `vars` was created to support loading different parameters for different stages. Take following as an example:
```yaml
stages:
  train_model:
    foreach: [us, uk]
    do:
      wdir: ${item}
      vars: params.yaml  # uk/params.yaml, uk/params.yaml, etc.
      cmd: cat params.yaml
```

But I don't find it very elegant, is cumbersome and haven't seen anyone use this. Hydra support may have made this redundant.

**Comment by efiop** [comment]
@dberenbaum Created https://github.com/iterative/dvc/issues/9561

**Comment by dberenbaum** [comment]
Thanks @efiop! Does #9561 relate to 3.0 items?

**Comment by dberenbaum** [comment]
@sjawhar That's a really creative way to do things! If we were to implement #5172, do you think that would solve the same use case? From what I can tell, you are limited by needing to loop over both sessions and features.

@skshetry WDYT about the comment from @sjawhar above? What do you think would be the best way to do it?

**Comment by efiop** [comment]
@dberenbaum I will try to create `dvc cache/remote check` if I have time this week and if I will - it will be nice to drop cache checks in a few places right away. If not - i think we can do that later, even though that's not ideal.

**Comment by skshetry** [comment]
@sjawhar, that's an interesting way to do nested looping with merge-key. 

How many sessions do you run? If they aren't that many, I'll suggest using a (duplicated) map/dictionary and use that loop.

```
# params.yaml
sessions:
  feature1_session1:
    key: feature_one
    input_dir: feature_one
  feature1_session2:
    key: feature_one
    input_dir: feature_one
  feature2_session1:
    key: feature_two
    input_dir: feature_two
  feature2_session2:
    key: feature_two
    input_dir: feature_two
```

This might be more readable, although you can still use the same merge-key to avoid duplications.

```
sessions:
  feature1_session1: &feature1
    key: feature_one
    input_dir: feature_one
  feature1_session2: *feature1
  ...
  feature2_session1: &feature2
    key: feature_two
    input_dir: feature_two
  feature2_session2: *feature2
  ...
```

#5172 might be a better solution to fix this.

**Comment by sjawhar** [comment]
> @sjawhar, that's an interesting way to do nested looping with merge-key.
> 
> How many sessions do you run? If they aren't that many, I'll suggest using a (duplicated) map/dictionary and use that loop.

@skshetry When we use DVC in a data registry pattern, there could be hundreds or thousands of sessions. Yes, though, you're right that we _could_ have an additional step the one runs before running `dvc` commands which generates this `params.yaml`, but supporting it natively in DVC seems more logical (to me at least)
