### ISSUE TITLE
Tracking fsspec related pending changes

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc#7543]
##### Fsspec Compatibility

- [ ] Make RepoFileSystem fsspec-compatible.
- [ ] Make LocalFileSystem fsspec-compatible.
- [ ] Make GitFileSystem fsspec-compatible
- [ ] Get rid of `FileSystem`.
- [ ] Get rid of `CallbackMixin` since callbacks are now generally supported.
- [ ] Get rid of `NoDirectoriesMixin`, merge with `HTTPFileSystem`.
- [ ] Reorganize/get-rid of `fs.utils`/`dvc.utils.fs`/`System`.

##### Post-fsspec changes

- [ ] Handle OSErrors instead of DvcExceptions.
- [ ] Rethink `Cloud` fixtures, so that they can work with any `fsspec`-compatible filesystems by default.
           Extract `Cloud.get_url()` and `Cloud.config` out of it.
