### ISSUE TITLE
`exp push`: minimize errors from pushing to dvc remote

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8678]
If none of my outputs are tracked by dvc, can I push my experiment without configuring a dvc remote? This will only push the git refs. This is useful for dvclive experiments onboarding, where I start saving exp refs before I set up dvc to track anything.

Edit: adding a checklist of related items to address:
- [ ] Don't fail due to remote config/access if there's nothing to push (https://github.com/iterative/dvc/issues/8678#issuecomment-1344696458)
- [x] Don't push cache for baseline commit (#6592)
- [ ] Clarify behavior when trying to use `dvc exp push` with cloud-versioned experiments (https://github.com/iterative/dvc/issues/8675#issuecomment-1452514510)

**Comment by dberenbaum** [comment]
🤦 Yup, that works

**Comment by dberenbaum** [comment]
Actually, still want to keep this open. I'd rather detect this automatically and not fail in cases where no remote is needed.

**Comment by dberenbaum** [comment]
A related feature request to make `exp push` simpler is for it to create a regular branch from the experiment and push that instead of the exp ref. Related to https://github.com/iterative/vscode-dvc/issues/3077 and https://github.com/iterative/dvc.org/pull/4172#discussion_r1065155477.

**Comment by efiop** [comment]
@dberenbaum Looks like I'm not fully following the scenario. You mean something like:

```
def test_push_no_dvc_outs(tmp_dir, scm, dvc, copy_script, git_upstream):
    tmp_dir.gen("params.yaml", "foo: 1")
    stage = dvc.run(
        cmd="python copy.py params.yaml metrics.yaml",
        params=["foo"],
        name="copy-file",
        deps=["copy.py"],
    )
    scm.add(["dvc.yaml", "dvc.lock", "copy.py", "params.yaml", "metrics.yaml", ".gitignore"])
    scm.commit("init")

    results = dvc.experiments.run(stage.addressing, params=["foo=2"])
    exp_rev = first(results)
    exp_ref = first(exp_refs_by_rev(scm, exp_rev))

    dvc.experiments.push(git_upstream.url, [exp_ref.name])
```

? Meaning there are just no `cache: True` kind of outputs, right? If so, I'm not able to reproduce so far with older and currect versions of dvc. So I'm pretty sure I'm misunderstanding something.

**Comment by efiop** [comment]
@daavoo Sorry for confusion. Yes, I'm talking about that one (well, this current issue from the issue description)

**Comment by efiop** [comment]
@dberenbaum I've tried 2.35.0 from back in november and was still not able to reproduce. Maybe there was some misunderstanding here?
