### ISSUE TITLE
exp show: improve performance and stability of collection for vs code

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#8787]
Per issues like https://github.com/iterative/dvc/issues/8762, `exp show` needs to collect faster and be more stable for vs code to work smoothly.

TODO
- [x] cache collected exp data (https://github.com/iterative/dvc/pull/9069)
- [x] gc celery messages (#8676)
- [x] investigate ref name performance (#9077)

**Comment by karajan1001** [comment]
Current severe problems

- [ ] #8622  
> hadn't look into it for now
- [ ] #8621  
> Currently I had use a granular lock in experiments, during the running the exp will only lock its own experiments reference, but because we had a shared reference `EXEC_CHECKPOINT`. need to make each experiments use its own `EXEC_CHECKPOINT`
- [ ] #8614
> Need a closer look, but I found another severe problem. Sometimes `queue worker` will not automatically shut down if something goes wrong inside it. 
- [ ] #8481 
> Hadn't look into it.
- [ ] #8478 In VSCode extension I can see the live metrics, like in https://user-images.githubusercontent.com/6745454/212892100-ae2d032d-e23b-4b62-9207-28752a3de4c8.mp4
- [ ] #8477 Can solve fetch, but push to a non-bare Git repo is not supported for `pygit2`, maybe we can use fetch instead of push. 
- [ ] #8763 Related to #8477 `push`
- [ ] #8762 Related to #8477 `fetch`, a new had been created. 
- [ ] #8676 Need to GC heartbeat messages, for now for every single task we create one heartbeat message per minute. 

One potential problem. I still got into `too many open files.` Error even if I used `git gc` to clean the Git repository.
