### ISSUE TITLE
Introduce `artifacts:` section in DVC and make it work with GTO

### ISSUE THREAD

**Issue by aguschin** [iterative/dvc#9219]
## Summary / Background

To make working with Model Registry (including Studio MR) more accessible for DVC users, we merge `artifacts.yaml` into DVC. More detail discussion on this https://github.com/iterative/gto/issues/337

## Release scope

Described in https://github.com/iterative/mlem.ai/pull/323, but summarizing it here. For now I'm excluding what we considered to be extra features (they can be found in docs proposal marked as `[extra for now]`):

- [x] adding top-level `registry:` section and exposing for API user (Studio) https://github.com/iterative/dvc/pull/9220
- [x] allow it to be read from a file instead of writing it in `dvc.yaml` completely, e.g. `registry: artifacts.yaml` https://github.com/iterative/dvc/pull/9220
- [x] https://github.com/iterative/dvclive/issues/519
- [x] updating `example-gto` repo and other fixture repos for Studio BE https://github.com/iterative/example-repos-dev/pull/192
- [x] DVC API to add an artifact https://github.com/iterative/dvc/pull/9345
- [x] switching Studio to new mechanics https://github.com/iterative/studio/issues/5704
- [x] removing `artifacts.yaml` part from GTO https://github.com/iterative/gto/pull/346
- [x] updating GTO GH action to work with new annotations format https://github.com/iterative/gto-action/tree/v2
- [ ] updating docs https://github.com/iterative/dvc.org/issues/4423 
- [x] update https://github.com/iterative/dvcyaml-schema https://github.com/iterative/dvcyaml-schema/pull/36
- [x] communication with customers/users to migrate from old MR to new MR

## Follow-ups after release (p1)
- [x] make a video showing e2e workflow (add/log->compare->register->assign/promote->download->deploy) to publish to YouTube/other channels
- [ ] https://github.com/iterative/gto/issues/354
- [ ] update example repos: demo-bank-customer-churn, example-get-started-experiments, demo-fashion, etc
- [x] follow-up on this for GTO users in https://github.com/iterative/gto/issues/337
- [x] update GTO action to be able to download artifacts https://github.com/iterative/gto-action/issues/17

## Follow-ups after release (p2)
- [ ] implementing `dvc get $REPO myartifact#prod` https://github.com/iterative/dvc/issues/9100
- [ ] implementing way to get `#prod` or `@latest` with DVC API
- [ ] consider https://github.com/iterative/dvc/issues/9102
- [ ] support `dvc import` for artifacts same way we should support `dvc get` already

## Related issues
- the `artifacts` piece @skshetry implemented already https://github.com/iterative/dvc/issues/8214 https://github.com/iterative/dvc/pull/8232

**Comment by shcheklein** [comment]
Thanks @aguschin, sounds like a good plan, overall. A few questions:

>  allow it to be read from a file instead of writing it in dvc.yaml completely, e.g. registry: artifacts.yaml

can we cut the scope? is it needed?

> updating docs

does it make sense to start with this? 

Do we need to include an item that simplifies GTO? (removes the registry files mechanics).

**Comment by dberenbaum** [comment]
> > updating docs
> 
> does it make sense to start with this?

@shcheklein I added https://github.com/iterative/dvc.org/issues/4423 to discuss docs. Since @aguschin already drafted https://github.com/iterative/mlem.ai/pull/323, is there something missing from there that you'd like to see before implementation?

> > allow it to be read from a file instead of writing it in dvc.yaml completely, e.g. registry: artifacts.yaml
> 
> can we cut the scope? is it needed?

I asked @aguschin the same thing 😄, and he explained that he will try to do it to make it easier for existing users to transition if it's low effort. I do worry about documenting this and making `dvc.yaml` even more complex, but I think we could try to minimize this. I would even consider not documenting it for now if it's strictly a legacy thing to help existing GTO users.

**Comment by shcheklein** [comment]
> can we cut the scope? is it needed?

Folks, we need to be extra extra mindful about complexity and scope. Can we help the existing users (and we don't have many, right?) to transition to the new format manually, of with some small written instruction? 

Complicating parsing in Studion, dvc.yaml format, etc - doesn't unfortunately sound like a very easy thing to do.

I feel your concerns and I like the deep care to the users though @aguschin !!

>  is there something missing from there that you'd like to see before implementation?

I don't know (your call), I was asking specifically because it sometimes uncovers more things. If you feel that it's stable already, we get sense for all the changes, etc - we good to go then.

**Comment by dberenbaum** [comment]
@aguschin We are aiming to include this as part of a 3.0 release at the end of this quarter. Do you expect that we can get all of the items above done? Do you think there is more that needs to be added before release?

**Comment by aguschin** [comment]
@dberenbaum, yes, I'm sure we'll get it done. And it looks like top issue's comment has all items to do.
