### ISSUE TITLE
import/get: meta-issue

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9296]
This issue collects improvements needed for `dvc import/get`:

- [x] Don't clone if repo is available locally (fixed in https://github.com/iterative/dvc/pull/9246)
- [x] Pull directories from source: https://github.com/iterative/dvc/issues/8872
- [x] Choosing a remote https://github.com/iterative/dvc/issues/2466
- [x] Configuring remote options (like AWS profile)
- [x] #9656 
- [x] `dvc remote/config --config myconfig`

p2/research issues for performance improvements:
- [ ] Filter clones (limit what is fetched for monorepos)
- [ ] Use bare repos
- [ ] Cache clones (probably need https://github.com/iterative/scmrepo/issues/204 first)
- [ ] Incremental updates: https://github.com/iterative/dvc/issues/8808
- [ ] Cache data

**Comment by efiop** [comment]
For the record: Edited first (fixed) and third (need scmrepo mirrors) points.

**Comment by dberenbaum** [comment]
@aguschin Any details you can add about monorepo support?

**Comment by aguschin** [comment]
No @dberenbaum. I'll add something when I start implementing `import/get` I think.

**Comment by pmrowla** [comment]
With regard to clone caching, do we want it to be configurable? I'm not sure having the caching as default behavior is ideal.

Right now if you import/get with a specific branch or tag name, we make a shallow clone with only that specific branch or tag. If a user has a giant git repo (which seems likely in the monorepo case), it is probably going to be faster for DVC to always make a new temporary shallow clone that only contains the specific thing they want to import than it would be for us to mirror their entire monorepo once and then re-use that cached mirror for future imports.

It seems to me that it would make more sense to have the caching be optional (and non-default).

**Comment by efiop** [comment]
@pmrowla Though global caching might not imply mirroring. We have caching within the session already, maybe there is a way to just make that global as is so we cache those shallow clones in `site_cache_dir`. And maybe there is a way to be smart about unshallowing them when we need to.

**Comment by dberenbaum** [comment]
Moved caching clones to the bottom of the checklist. I think what @efiop suggested makes sense, but if it's overly complex and/or isn't likely to be a major performance improvement, we can skip this item.

**Comment by efiop** [comment]
For the record: all main tasks are done now.
