### ISSUE TITLE
Epic: limit cache validation to absolute necessity

### ISSUE THREAD

**Issue by efiop** [iterative/dvc#9561]
We validate cache too much, almost every operation (status/repro/checkout/etc) does it every time and even though they don't rehash the files, it still takes a lot of time to validate cache for large datasets. This is mostly a leftover from our old hardlink/symlink defaults.

- [ ] introduce `dvc cache/remote check` (or some other name)
- [ ] don't validate on checkout
- [ ] don't validate on status (unless explicitly asked?)
- [ ] don't validate on repro
- [ ] ...
