### ISSUE TITLE
Epic: params/metrics/plots collection

### ISSUE THREAD

**Issue by dberenbaum** [iterative/dvc#9722]
p1:
- [x] https://github.com/iterative/studio/issues/4912
- [ ] https://github.com/iterative/dvc/issues/9588
- [x] https://github.com/iterative/dvc/issues/9478

p2:
- [x] https://github.com/iterative/dvc/issues/9452

**Comment by dberenbaum** [comment]
@skshetry Would you be able to take this?

**Comment by shcheklein** [comment]
On the current `example-get-started`.

- `dvc metrics diff` is not working anymore (we moved metrics to cache)
- `dvc metrics diff` is slow:

```
(.venv) √ Projects/example-get-started % time dvc metrics diff
dvc metrics diff  0.47s user 0.17s system 24% cpu 2.617 total
```

```
2023-09-09 15:51:34,438 TRACE:    16.88 ms in collecting stages from /Users/ivan/Projects/example-get-started
2023-09-09 15:51:34,438 TRACE:    36.50 mks in collecting stages from /Users/ivan/Projects/example-get-started/.github
2023-09-09 15:51:34,439 TRACE:     2.37 mks in collecting stages from /Users/ivan/Projects/example-get-started/.github/workflows
2023-09-09 15:51:34,440 TRACE:   831.29 mks in collecting stages from /Users/ivan/Projects/example-get-started/data
2023-09-09 15:51:34,440 TRACE:     4.38 mks in collecting stages from /Users/ivan/Projects/example-get-started/src
```

-

**Comment by skshetry** [comment]
@shcheklein, the first one should be addressed by #9909. 

Not sure what's going on with the performance, but I don't see it getting faster with my PR. in fact, it might be slower with path expansions for the directories (at least until it gets cached in the index from what I see). On successive invocations, the actual metric and param files are not cached by default unlike in plots, so it'll hit remote every time unless you do `dvc fetch`.

**Comment by shcheklein** [comment]
I guess, we'll have to introduce some caching, otherwise `dvc exp show` can be very slow even on a basic repo like example-get-started (in its current state, where we track metrics with DVC).

**Comment by dberenbaum** [comment]
Dropping https://github.com/iterative/dvc/issues/9588 from the scope and closing this
